#!/usr/bin/env python3
"""Fail the build when a page references a file that is not there.

Nothing else catches this. Zola resolves the links between pages, and
`zola check` verifies those, but a stylesheet, a script, a font or an image is
just a string in an attribute: rename `search.js` and every page still builds,
still passes every other check, and ships with search quietly broken.

check-js-runtime.py names this file in its list of what it does not catch,
because Chrome reports a failed subresource to devtools rather than to stderr,
so a 404 stylesheet does not raise anything the browser check can see.

Walks the built HTML, collects every src, href and srcset that points at this
site, and checks the file exists in public/. Skips other origins, mailto, tel,
data and fragment links, and the page URLs Zola already verified.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Dict, List, Set
from urllib.parse import unquote, urlparse

from _common import BASE_URL, PUBLIC_DIR

# Attributes that name a file rather than a page. Page links are Zola's job.
# Unquoted values are matched too: this can run before or after minify, and the
# minified HTML drops the quotes, which is how the first version of this check
# read 468 files and still missed a deleted navigation.js.
ASSET_ATTR = re.compile(
    r'''(?:src|href|srcset|content)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))''', re.I)

# What an asset reference looks like: anything with one of these extensions.
ASSET_SUFFIXES = (
    '.css', '.js', '.mjs', '.json', '.xml', '.txt', '.md',
    '.woff', '.woff2', '.ttf', '.otf', '.eot',
    '.jpg', '.jpeg', '.png', '.gif', '.webp', '.avif', '.svg', '.ico',
    '.pdf', '.zip', '.asc',
)

SKIP_PREFIXES = ('mailto:', 'tel:', 'data:', 'javascript:', '#', '//')


def candidate_paths(value: str) -> List[str]:
    """Every URL inside one attribute. srcset holds several, comma separated."""
    parts = [value] if ',' not in value else [p.strip() for p in value.split(',')]
    urls = []
    for part in parts:
        # a srcset entry is "<url> <descriptor>"; the descriptor is not a URL
        url = part.strip().split(' ')[0].strip()
        if url:
            urls.append(url)
    return urls


def to_public_path(url: str) -> Path | None:
    """Where a referenced asset should live in public/, or None to skip it."""
    url = url.replace('&#x2F;', '/').replace('&amp;', '&').strip()
    if not url or url.startswith(SKIP_PREFIXES):
        return None
    if url.startswith('http'):
        if not url.startswith(BASE_URL):
            return None
        url = url[len(BASE_URL):] or '/'
    if not url.startswith('/'):
        return None

    path = unquote(urlparse(url).path)
    if not path.lower().endswith(ASSET_SUFFIXES):
        return None
    return PUBLIC_DIR / path.lstrip('/')


def main() -> None:
    if not PUBLIC_DIR.is_dir():
        sys.exit(f'{PUBLIC_DIR}/ is missing: run `zola build` first')

    missing: Dict[str, Set[str]] = {}
    checked: Set[Path] = set()
    pages = 0

    for page in PUBLIC_DIR.rglob('*.html'):
        # The slide decks are generated by Marp and carry their own assets.
        if 'slides' in page.parts:
            continue
        pages += 1
        html = page.read_text(encoding='utf-8', errors='replace')
        for groups in ASSET_ATTR.findall(html):
            value = next((g for g in groups if g), '')
            for url in candidate_paths(value):
                target = to_public_path(url)
                if target is None:
                    continue
                checked.add(target)
                if not target.is_file():
                    missing.setdefault(str(target.relative_to(PUBLIC_DIR)), set()).add(
                        str(page.relative_to(PUBLIC_DIR)))

    if missing:
        print(f'{len(missing)} referenced file(s) are not in {PUBLIC_DIR}/:', file=sys.stderr)
        for target, sources in sorted(missing.items()):
            listed = ', '.join(sorted(sources)[:3])
            more = f' (+{len(sources) - 3} more)' if len(sources) > 3 else ''
            print(f'  {target}\n      referenced by {listed}{more}', file=sys.stderr)
        sys.exit(1)

    print(f'  {len(checked)} referenced files all present, across {pages} pages')


if __name__ == '__main__':
    main()
