#!/usr/bin/env python3
"""Fail the build when a page uses an icon the Font Awesome subset does not carry.

static/css/fontawesome.min.css holds only the icons the site uses, generated by
scripts/subset-fontawesome.py. Adding an `fa-*` class without regenerating the
subset would ship a blank box, and nothing else would complain. This walks the
built HTML and checks every icon class resolves to a selector in the CSS.

Stdlib only, so it runs in CI like the other post-build scripts.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Dict, Set

PUBLIC_DIR = Path("public")
CSS_PATH = Path("static/css/fontawesome.min.css")

# Marp decks are self-contained builds and do not use the site stylesheet.
SKIP_DIRS = ("slides",)

CLASS_ATTR = re.compile(r'class="([^"]*\bfa-[^"]*)"')
CSS_SELECTOR = re.compile(r"\.(fa-[a-z0-9-]+)")


def css_classes() -> Set[str]:
    css = CSS_PATH.read_text(encoding="utf-8")
    return set(CSS_SELECTOR.findall(css))


def used_classes() -> Dict[str, str]:
    """Every fa-* class in the built HTML, mapped to the first page using it."""
    found: Dict[str, str] = {}
    for path in PUBLIC_DIR.rglob("*.html"):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        html = path.read_text(encoding="utf-8", errors="ignore")
        for attr in CLASS_ATTR.findall(html):
            for token in attr.split():
                if token.startswith("fa-"):
                    found.setdefault(token, str(path))
    return found


def main() -> int:
    if not CSS_PATH.is_file():
        print(f"{CSS_PATH} is missing", file=sys.stderr)
        return 1

    known = css_classes()
    used = used_classes()
    missing = {cls: page for cls, page in used.items() if cls not in known}

    if missing:
        print("Icon classes with no rule in the Font Awesome subset:", file=sys.stderr)
        for cls, page in sorted(missing.items()):
            print(f"  {cls}  (first seen in {page})", file=sys.stderr)
        print(
            "\nRegenerate the subset:  python3 scripts/subset-fontawesome.py",
            file=sys.stderr,
        )
        return 1

    print(f"All {len(used)} icon classes resolve.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
