#!/usr/bin/env python3
"""Fail the build when a page uses an icon the Font Awesome subset does not carry.

static/css/fontawesome.min.css and the woff2 files next to it hold only the icons
the site uses, generated by scripts/subset-fontawesome.py. Adding an `fa-*` class
without regenerating the subset would ship a blank box, and nothing else would
complain. This checks the built HTML three ways:

1. Every class naming an icon upstream knows about must be in the subset manifest,
   which lists the glyphs really present in the generated fonts.
2. Every other `fa-*` class (fa-fw, fa-spin, sizing helpers) must still resolve to
   a selector in the generated CSS.
3. No script may assemble an icon class at runtime, because a name built from a
   variable is invisible both to the subsetter and to this check.

Stdlib only, so it runs in CI like the other post-build scripts.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

PUBLIC_DIR = Path("public")
CSS_PATH = Path("static/css/fontawesome.min.css")
SOURCE_CSS = Path("tools/fontawesome/fontawesome.min.css")
MANIFEST = Path("tools/fontawesome/subset-manifest.json")

# Marp decks are self-contained builds and do not use the site stylesheet.
SKIP_DIRS = ("slides",)

CLASS_ATTR = re.compile(r'class="([^"]*\bfa-[^"]*)"')
CSS_SELECTOR = re.compile(r"\.(fa-[a-z0-9-]+)")
UPSTREAM_ICON = re.compile(r"\.fa-([a-z0-9-]+):before")
# `'fa-' + name`, `"fa-" + kind`, `` `fa-${name}` ``
DYNAMIC_CLASS = re.compile(r"""fa-\$\{|['"]fa-['"]\s*\+|\+\s*['"]fa-""")
SCRIPT_SOURCES = ("static/**/*.js", "templates/**/*.html")


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def shipped_icons() -> set[str]:
    """The icon names the subset manifest says are in the generated fonts.

    The manifest is `{"house": "f015", ...}`, so iterating it yields names. It is
    generated by subset-fontawesome.py, but json.loads returns Any, so a manifest
    that had drifted to a list of `fa-`-prefixed names would still `set()` cleanly
    here and quietly change what every comparison below means. Check it once."""
    raw = json.loads(read(MANIFEST))
    if not isinstance(raw, dict) or not all(
        isinstance(name, str) and isinstance(cp, str) for name, cp in raw.items()
    ):
        raise SystemExit(
            f"{MANIFEST} should be an object of icon name to hex codepoint. "
            "Regenerate it:  python3 scripts/subset-fontawesome.py"
        )
    return set(raw)


def used_classes() -> dict[str, str]:
    """Every fa-* class in the built HTML, mapped to the first page using it."""
    found: dict[str, str] = {}
    for path in PUBLIC_DIR.rglob("*.html"):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        for attr in CLASS_ATTR.findall(read(path)):
            for token in attr.split():
                if token.startswith("fa-"):
                    found.setdefault(token, str(path))
    return found


def dynamic_class_sites() -> dict[str, str]:
    """Files that assemble an icon class from a variable, with the snippet found."""
    offenders: dict[str, str] = {}
    for pattern in SCRIPT_SOURCES:
        for path in Path().glob(pattern):
            text = read(path)
            match = DYNAMIC_CLASS.search(text)
            if match:
                start = max(match.start() - 30, 0)
                offenders[str(path)] = " ".join(text[start : match.end() + 30].split())
    return offenders


def fail(message: str) -> int:
    print(message, file=sys.stderr)
    print(
        "\nRegenerate the subset:  python3 scripts/subset-fontawesome.py",
        file=sys.stderr,
    )
    return 1


def main() -> int:
    for path in (CSS_PATH, SOURCE_CSS, MANIFEST):
        if not path.is_file():
            print(f"{path} is missing", file=sys.stderr)
            return 1

    shipped = shipped_icons()
    subset_selectors = set(CSS_SELECTOR.findall(read(CSS_PATH)))
    upstream_icons = set(UPSTREAM_ICON.findall(read(SOURCE_CSS)))

    # The manifest describes the fonts; the CSS has to agree, or a class resolves to
    # a glyph the stylesheet never points at.
    orphaned = sorted(
        f"fa-{name}" for name in shipped if f"fa-{name}" not in subset_selectors
    )
    if orphaned:
        return fail(
            "the subset manifest lists icons with no rule in the generated CSS: "
            + ", ".join(orphaned)
        )

    used = used_classes()
    missing_icon: dict[str, str] = {}
    missing_rule: dict[str, str] = {}
    for cls, page in used.items():
        name = cls[len("fa-") :]
        if name in upstream_icons:
            if name not in shipped:
                missing_icon[cls] = page
        elif cls not in subset_selectors:
            missing_rule[cls] = page

    if missing_icon or missing_rule:
        lines = [
            f"  {cls}  no glyph in the subset  (first seen in {page})"
            for cls, page in sorted(missing_icon.items())
        ] + [
            f"  {cls}  no rule in the subset CSS  (first seen in {page})"
            for cls, page in sorted(missing_rule.items())
        ]
        return fail(
            "Icon classes the Font Awesome subset does not cover:\n" + "\n".join(lines)
        )

    offenders = dynamic_class_sites()
    if offenders:
        lines = [f"  {path}: {snippet}" for path, snippet in sorted(offenders.items())]
        print(
            "Icon classes assembled at runtime cannot be verified, so the subset may\n"
            "not carry them. Write the full class name as a literal instead:\n"
            + "\n".join(lines),
            file=sys.stderr,
        )
        return 1

    print(f"All {len(used)} icon classes resolve, {len(shipped)} glyphs in the subset.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
